### ISSUE TITLE
Add windowed mode

### ISSUE THREAD

**Issue by chaptergy** [futo-org/fcast#5]
On desktop devices it is not desireable to have a fullscreen overlay showing it is waiting for connections which does not go away. Maybe this is a Linux specific problem, as it never appears as a tray icon. Linux Mint with Cinnamon to be specific.

**Comment by Zvonimir-FUTO** [comment]
There should be text at the bottom saying "App will continue to run as tray app when the window is closed" and after closing it it goes into tray.

**Comment by Michael-Hollister** [comment]
In the next release I'll change the default behavior to start in windowed mode. In the meantime, you can press F11 to exit full screen or press ALT to bring up the menu bar to exit or minimize the application.

**Comment by Michael-Hollister** [comment]
Closing issue now that a new release is available with this change.
